version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - .:/usr/src/app/static
    ports:
      - 8000:8000
  #   environment:
  #     - SECRET_KEY=foo
  #     - DJANGOPROJECT_DATA_DIR=./data
  #     - DJANGO_SETTINGS_MODULE=djangoproject.settings.docker
  #     - SQL_ENGINE=django.db.backends.mysql
  #     - SQL_DATABASE=djangoproject
  #     - SQL_USER=djangoproject
  #     - SQL_PASSWORD=secret
  #     - SQL_HOST=db
  #     - SQL_PORT=3306
  #   depends_on:
  #     - db
  # db:
  #   image: mysql:11.2-alpine
  #   environment:
  #     - mysql_USER=djangoproject
  #     - mysql_PASSWORD=secret
  #     - mysql_DB=djangoproject
